export = {
  PORT: 'PORT',
  LOG_LEVEL: 'LOG_LEVEL',
  CREATE_SWAGGER_FILE: 'CREATE_SWAGGER_FILE',
  CACHE_STD_TTL: 'CACHE_STD_TTL',
  MAX_WAITING_TIME_FOR_PLAYER_2: 'MAX_WAITING_TIME_FOR_PLAYER_2',
  SENTRY_DSN: 'SENTRY_DSN',
  SENTRY_TRACES_SAMPLE_RATE: 'SENTRY_TRACES_SAMPLE_RATE',
  ENVIRONMENT: 'ENVIRONMENT'
};
