name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
