name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Echo sentry token
        run: echo "This is the env var $SENTRY_AUTH_TOKEN .!"

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
